### ISSUE TITLE
Hi,apolcyn. Could you please write some documents for the awesome traclus_impl?

### ISSUE THREAD

**Issue by AllenShow** [apolcyn/traclus_impl#1]
Hi apolcyn! Many thanks to your contribution to traclus_impl. As the first pass implementation for TRACLUS, traclus_impl is absolutely a good tool for users. However, if someone is new to the module, he/she may not know how to use. So could you please provide some user documents? Such as how to get started, the format of the data sets, instructions for each function, and many more, with these, the traclus_impl would be more perfect. Thank you very much.

**Comment by apolcyn** [comment]
Hi AllenShow,

No problem, I'm just starting to work now on making this more usable now.
I'm now working on making all of the tests runnable and adding them all to the pypi package. I'll put up some usage instructions soon.

**Comment by apolcyn** [comment]
updated with a readme, all tests should now be runnable from command line when installed too.
