### ISSUE TITLE
Output (y,x) Coordinates

### ISSUE THREAD

**Issue by max-schaeufele91** [apolcyn/traclus_impl#10]
Your implementation really helped me for a project in my studies, but I was wondering if there is a mistake in the format of the output file. 

I would suppose that the rep. trajectories would have the format [(x,y), (x,y),...] but instead it is [(y,x), (y,x),...]. So, are the coordinates transposed or is this a mistake in the description of the output file. 

I couldn't find the solution by myself. I would be very grateful for the clarification.

**Comment by overdoz** [comment]
U have to swap the output values by your own :/
